services:
  garage:
    image: ghcr.io/dhrandy/garage:latest
    container_name: garage
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./data:/app/data
    environment:
      - TZ=${TZ:-UTC}
    ports:
      - 8917:8000
